spring:
  profiles:
    active: dev

---
server:
  port: 8787

spring:
  profiles: dev
  application:
    name: zuul #此实例注册到eureka服务端的name
    redis:
      host: 208.167.255.217
      port: 6379

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:3000/eureka/
  instance:
    instance-id: zuul #此实例注册到eureka服务端的唯一的实例ID
    prefer-ip-address: true #是否显示IP地址
    leaseRenewalIntervalInSeconds: 10 #eureka客户需要多长时间发送心跳给eureka服务器，表明它仍然活着,默认为30 秒 (与下面配置的单位都是秒)
    leaseExpirationDurationInSeconds: 30 #Eureka服务器在接收到实例的最后一次发出的心跳后，需要等待多久才可以将此实例删除，默认为90秒

zuul:
  ignored-services: "*" #禁止服务通过服务名访问

---
spring:
  profiles: test
  application:
    name: zuul #此实例注册到eureka服务端的name
    redis:
      host: 208.167.255.217
      port: 6379

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:3000/eureka/
  instance:
    instance-id: zuul #此实例注册到eureka服务端的唯一的实例ID
    prefer-ip-address: true #是否显示IP地址
    leaseRenewalIntervalInSeconds: 10 #eureka客户需要多长时间发送心跳给eureka服务器，表明它仍然活着,默认为30 秒 (与下面配置的单位都是秒)
    leaseExpirationDurationInSeconds: 30 #Eureka服务器在接收到实例的最后一次发出的心跳后，需要等待多久才可以将此实例删除，默认为90秒

zuul:
  ignored-services: "*" #禁止服务通过服务名访问
  routes:
    custom:
      serviceId: customId
      path: /custom/**